# ─────────────────────────────────────────────
# SSH key pair — generated by Terraform, saved locally as simpleqna.pem
# ─────────────────────────────────────────────

resource "tls_private_key" "ec2_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "ec2_key" {
  key_name   = "simpleqna-key"
  public_key = tls_private_key.ec2_key.public_key_openssh

  tags = {
    Project = "SimpleQnA"
  }
}

resource "local_sensitive_file" "private_key" {
  content         = tls_private_key.ec2_key.private_key_pem
  filename        = "${path.module}/simpleqna.pem"
  file_permission = "0400"
}

# ─────────────────────────────────────────────
# AMI — latest Ubuntu 24.04 LTS (x86_64)
# ─────────────────────────────────────────────

data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

# ─────────────────────────────────────────────
# Security group
# ─────────────────────────────────────────────

resource "aws_security_group" "backend" {
  name        = "simpleqna-backend-sg"
  description = "Allow backend API and SSH access"

  ingress {
    description = "FastAPI backend"
    from_port   = 8000
    to_port     = 8000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Project = "SimpleQnA"
  }
}

# ─────────────────────────────────────────────
# EC2 instance (Ubuntu 24.04)
# remote-exec installs Docker via the official apt repo then starts the stack
# ─────────────────────────────────────────────

resource "aws_instance" "backend" {
  ami                         = data.aws_ami.ubuntu.id
  instance_type               = "t3.micro"
  key_name                    = aws_key_pair.ec2_key.key_name
  vpc_security_group_ids      = [aws_security_group.backend.id]
  associate_public_ip_address = true

  connection {
    type        = "ssh"
    user        = "ubuntu"
    private_key = tls_private_key.ec2_key.private_key_pem
    host        = self.public_ip
  }

  provisioner "file" {
    content     = <<-SCRIPT
      #!/bin/bash
      set -e

      # Install Docker via official apt repo (https://docs.docker.com/engine/install/ubuntu/)
      sudo apt-get update -y
      sudo apt-get install -y ca-certificates curl git
      sudo install -m 0755 -d /etc/apt/keyrings
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
      sudo chmod a+r /etc/apt/keyrings/docker.asc
      ARCH=$(dpkg --print-architecture)
      CODENAME=$(. /etc/os-release && echo "$VERSION_CODENAME")
      echo "deb [arch=$ARCH signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $CODENAME stable" \
        | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt-get update -y
      sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      sudo systemctl start docker
      sudo systemctl enable docker

      # Clone repo
      sudo git clone ${var.github_repo} /app

      # Write .env
      sudo bash -c 'echo "LLM_API_KEY=${var.llm_api_key}" > /app/.env'
      sudo bash -c 'echo "SYSTEM_PROMPT=${var.system_prompt}" >> /app/.env'

      # Start all services
      cd /app && sudo docker compose up -d
      echo "✓ Backend stack is up"
    SCRIPT
    destination = "/tmp/setup.sh"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod +x /tmp/setup.sh",
      "/tmp/setup.sh"
    ]
  }

  tags = {
    Name    = "simpleqna-backend"
    Project = "SimpleQnA"
  }
}
